[project]
name = "ml-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "GPL-3.0-only"
authors = [{ name = "NextFire", email = "git@yuru.moe" }]
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = ["gemma-4", "llm-forcedaligner", "mms", "qwen3-forcedaligner"]

# [tool.uv.sources]
# torch = { index = "pytorch-cu126" }
# torchaudio = { index = "pytorch-cu126" }
# torchcodec = { index = "pytorch-cu126" }
# torchvision = { index = "pytorch-cu126" }

# [[tool.uv.index]]
# name = "pytorch-cu126"
# url = "https://download.pytorch.org/whl/cu126"
# explicit = true
